name: "Release new version of the script"
on:
  #schedule:
    # Every Tuesday at 3pm (whatever timezone is used?)
  #  - cron: 0 15 * * TUE
  push

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: check out gh-pages branch (where we release in)
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: check if script was updated and release new version
        run: |
          cd "${GITHUB_WORKSPACE}/master"
          bash release.sh