name: "XML Validity Check"
on:
  pull_request:
    branches:
      - main

jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Validate XML
        run: xmllint --noout mudlet-mapper.xml
